# Generated by Django 6.0.7 on 2026-07-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='ec_candidate_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Election Commission Candidate ID'),
        ),
    ]
