# Generated by Django 6.0.7 on 2026-07-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fix_ec_candidate_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawscrapeddata',
            name='source_url',
            field=models.URLField(db_index=True, max_length=2000, verbose_name='Source URL'),
        ),
    ]
