# Generated by Django 6.0.7 on 2026-07-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_rawscrapeddata_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='is_minister',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Minister'),
        ),
        migrations.AddField(
            model_name='politician',
            name='minister_title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Minister Title (English)'),
        ),
        migrations.AddField(
            model_name='politician',
            name='minister_title_kn',
            field=models.CharField(blank=True, max_length=255, verbose_name='Minister Title (Kannada)'),
        ),
        migrations.AddField(
            model_name='politician',
            name='minister_type',
            field=models.CharField(blank=True, choices=[('cm', 'Chief Minister'), ('deputy_cm', 'Deputy Chief Minister'), ('cabinet_minister', 'Cabinet Minister'), ('minister_of_state', 'Minister of State')], max_length=30, verbose_name='Minister Type'),
        ),
        migrations.AddField(
            model_name='politician',
            name='portfolio_en',
            field=models.TextField(blank=True, verbose_name='Portfolio Description (English)'),
        ),
        migrations.AddField(
            model_name='politician',
            name='portfolio_kn',
            field=models.TextField(blank=True, verbose_name='Portfolio Description (Kannada)'),
        ),
    ]
