# Generated by Django 6.0.7 on 2026-07-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_politician_is_minister_politician_minister_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='is_union_minister',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Union Minister'),
        ),
        migrations.AddField(
            model_name='politician',
            name='parliamentary_constituency_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Parliamentary Constituency (English)'),
        ),
        migrations.AddField(
            model_name='politician',
            name='parliamentary_constituency_kn',
            field=models.CharField(blank=True, max_length=255, verbose_name='Parliamentary Constituency (Kannada)'),
        ),
        migrations.AddField(
            model_name='politician',
            name='representative_type',
            field=models.CharField(choices=[('mla', 'Member of Legislative Assembly (MLA)'), ('mp_ls', 'Member of Parliament - Lok Sabha (MP)'), ('mp_rs', 'Member of Parliament - Rajya Sabha (MP)')], db_index=True, default='mla', max_length=20, verbose_name='Representative Type'),
        ),
        migrations.AddField(
            model_name='politician',
            name='union_portfolio_en',
            field=models.TextField(blank=True, verbose_name='Union Portfolio (English)'),
        ),
        migrations.AddField(
            model_name='politician',
            name='union_portfolio_kn',
            field=models.TextField(blank=True, verbose_name='Union Portfolio (Kannada)'),
        ),
        migrations.AddField(
            model_name='politician',
            name='union_title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Union Minister Title (English)'),
        ),
        migrations.AddField(
            model_name='politician',
            name='union_title_kn',
            field=models.CharField(blank=True, max_length=255, verbose_name='Union Minister Title (Kannada)'),
        ),
    ]
