# Generated by Django 6.0.7 on 2026-07-24 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_politician_is_union_minister_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='pop_buddhist_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Buddhist Population (%)'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='pop_christian_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Christian Population (%)'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='pop_hindu_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hindu Population (%)'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='pop_jain_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Jain Population (%)'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='pop_muslim_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Muslim Population (%)'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='pop_sc_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Scheduled Caste Population (%)'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='pop_sikh_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sikh Population (%)'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='pop_st_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Scheduled Tribe Population (%)'),
        ),
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election_year', models.PositiveSmallIntegerField(db_index=True, verbose_name='Election Year')),
                ('election_type', models.CharField(choices=[('assembly', 'Karnataka Legislative Assembly'), ('lok_sabha', 'Lok Sabha')], default='assembly', max_length=20, verbose_name='Election Type')),
                ('constituency_name', models.CharField(max_length=150, verbose_name='Constituency Name')),
                ('party_name', models.CharField(max_length=100, verbose_name='Party Name')),
                ('total_electors', models.BigIntegerField(default=0, verbose_name='Total Electors')),
                ('total_votes_polled', models.BigIntegerField(default=0, verbose_name='Total Votes Polled')),
                ('votes_secured', models.BigIntegerField(default=0, verbose_name='Votes Secured')),
                ('vote_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Vote Percentage')),
                ('margin_votes', models.BigIntegerField(default=0, verbose_name='Margin of Victory / Loss')),
                ('is_winner', models.BooleanField(default=True, verbose_name='Is Winner')),
                ('evm_votes', models.BigIntegerField(default=0, verbose_name='EVM Votes')),
                ('postal_votes', models.BigIntegerField(default=0, verbose_name='Postal Votes')),
                ('runner_up_name', models.CharField(blank=True, max_length=150, verbose_name='Runner-up Candidate')),
                ('runner_up_party', models.CharField(blank=True, max_length=100, verbose_name='Runner-up Party')),
                ('runner_up_votes', models.BigIntegerField(default=0, verbose_name='Runner-up Votes')),
                ('runner_up_vote_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Runner-up Vote Percentage')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electoral_results', to='core.politician', verbose_name='Politician')),
            ],
            options={
                'verbose_name': 'Election Result',
                'verbose_name_plural': 'Election Results',
                'ordering': ['-election_year'],
                'indexes': [models.Index(fields=['politician', '-election_year'], name='core_electi_politic_28a416_idx'), models.Index(fields=['election_year', 'election_type'], name='core_electi_electio_f13149_idx')],
            },
        ),
    ]
