# Generated by Django 6.0.7 on 2026-07-31 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_constituency_pop_buddhist_pct_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='constituency',
            name='core_consti_constit_8841c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='constituency',
            name='core_consti_distric_7801ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='constituency',
            name='core_consti_constit_362a48_idx',
        ),
        migrations.RemoveIndex(
            model_name='constituency',
            name='core_consti_constit_ee30ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='district',
            name='core_distri_distric_7697ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='district',
            name='core_distri_region_09e84f_idx',
        ),
        migrations.RemoveIndex(
            model_name='politician',
            name='core_politi_full_na_029c1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='politician',
            name='core_politi_current_773173_idx',
        ),
        migrations.RemoveIndex(
            model_name='politician',
            name='core_politi_current_cc517d_idx',
        ),
        migrations.RemoveIndex(
            model_name='politician',
            name='core_politi_is_acti_31749f_idx',
        ),
        migrations.RemoveIndex(
            model_name='politician',
            name='core_politi_is_veri_271107_idx',
        ),
        migrations.AddField(
            model_name='publicrecord',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publicrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='sex_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Sex Ratio (per 1000 males)'),
        ),
        migrations.AlterField(
            model_name='electionresult',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='electionresult',
            index=models.Index(fields=['politician', 'election_type'], name='core_electi_politic_a5ad15_idx'),
        ),
    ]
