# Generated by Django 6.0.7 on 2026-08-21 20:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_timestamp_to_publicrecord_and_clean_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeTenure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office_type', models.CharField(choices=[('mla', 'Member of Legislative Assembly (MLA)'), ('mp_ls', 'Member of Parliament - Lok Sabha (MP)'), ('mp_rs', 'Member of Parliament - Rajya Sabha (MP)'), ('cm', 'Chief Minister'), ('deputy_cm', 'Deputy Chief Minister'), ('cabinet_minister', 'Cabinet Minister'), ('minister_of_state', 'Minister of State'), ('union_minister', 'Union Minister'), ('other', 'Other')], db_index=True, max_length=50, verbose_name='Office Type')),
                ('office_title', models.CharField(blank=True, max_length=255, verbose_name='Office Title / Portfolio')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_current', models.BooleanField(db_index=True, default=False, verbose_name='Is Current')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Source URL')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_representatives', to='core.constituency', verbose_name='Constituency')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_tenures', to='core.politician', verbose_name='Politician')),
            ],
            options={
                'verbose_name': 'Office Tenure',
                'verbose_name_plural': 'Office Tenures',
                'ordering': ['-start_date', '-is_current'],
                'indexes': [models.Index(fields=['politician', 'is_current'], name='core_office_politic_e7d400_idx'), models.Index(fields=['politician', 'office_type'], name='core_office_politic_5e34aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_current', models.BooleanField(db_index=True, default=False, verbose_name='Is Current')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Source URL')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_members', to='core.party', verbose_name='Party')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_memberships', to='core.politician', verbose_name='Politician')),
            ],
            options={
                'verbose_name': 'Party Membership',
                'verbose_name_plural': 'Party Memberships',
                'ordering': ['-start_date', '-is_current'],
                'indexes': [models.Index(fields=['politician', 'is_current'], name='core_partym_politic_173370_idx'), models.Index(fields=['party', 'is_current'], name='core_partym_party_i_fe3343_idx')],
            },
        ),
    ]
