# Generated by Django 6.0.7 on 2026-08-21 20:14

from django.db import migrations


def seed_current_snapshots(apps, schema_editor):
    Politician = apps.get_model('core', 'Politician')
    PartyMembership = apps.get_model('core', 'PartyMembership')
    OfficeTenure = apps.get_model('core', 'OfficeTenure')

    for pol in Politician.objects.all():
        # Seed PartyMembership
        if pol.current_party:
            PartyMembership.objects.create(
                politician=pol,
                party=pol.current_party,
                is_current=True,
                is_verified=False,  # Unverified unless a direct source URL existed
                start_date=None,
                end_date=None
            )

        # Seed OfficeTenure: Representative Type (e.g., MLA, MP)
        if pol.representative_type:
            title = "Member of Legislative Assembly"
            if pol.representative_type == 'mp_ls':
                title = "Member of Parliament - Lok Sabha"
            elif pol.representative_type == 'mp_rs':
                title = "Member of Parliament - Rajya Sabha"
                
            OfficeTenure.objects.create(
                politician=pol,
                office_type=pol.representative_type,
                office_title=title,
                constituency=pol.current_constituency,
                is_current=True,
                is_verified=False,
                start_date=None,
                end_date=None
            )

        # Seed OfficeTenure: State Minister
        if pol.is_minister and pol.minister_type:
            title = pol.minister_title_en if pol.minister_title_en else "Minister"
            OfficeTenure.objects.create(
                politician=pol,
                office_type=pol.minister_type,
                office_title=title,
                constituency=pol.current_constituency,
                is_current=True,
                is_verified=False,
                start_date=None,
                end_date=None
            )

        # Seed OfficeTenure: Union Minister
        if pol.is_union_minister:
            title = pol.union_title_en if pol.union_title_en else "Union Minister"
            OfficeTenure.objects.create(
                politician=pol,
                office_type='union_minister',
                office_title=title,
                constituency=pol.current_constituency,
                is_current=True,
                is_verified=False,
                start_date=None,
                end_date=None
            )


def reverse_seed(apps, schema_editor):
    PartyMembership = apps.get_model('core', 'PartyMembership')
    OfficeTenure = apps.get_model('core', 'OfficeTenure')
    PartyMembership.objects.all().delete()
    OfficeTenure.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_officetenure_partymembership'),
    ]

    operations = [
        migrations.RunPython(seed_current_snapshots, reverse_seed),
    ]
