# Generated by Django 6.0.7 on 2026-08-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_temporal_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionresult',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AddField(
            model_name='electionresult',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Source URL'),
        ),
    ]
