from django.core.management.base import BaseCommand
from django.utils.text import slugify
from politicians_tracker.apps.core.models import Politician, Party, FinancialDeclaration

KARNATAKA_MPS = [
    {
        'first_name_en': 'Priyanka',
        'last_name_en': 'Jarkiholi',
        'full_name_en': 'Priyanka Jarkiholi',
        'full_name_kn': 'ಪ್ರಿಯಾಂಕಾ ಜಾರಕಿಹೊಳಿ',
        'slug': 'priyanka-jarkiholi',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Chikkodi',
        'parliamentary_constituency_kn': 'ಚಿಕ್ಕೋಡಿ',
        'party_short_name': 'INC',
        'age': 27,
        'gender': 'female',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/priyanka_jarkiholi.jpg',
        'terms_as_mp': 1,
        'biography_en': 'Priyanka Jarkiholi is a Member of Parliament representing the Chikkodi Lok Sabha constituency in Karnataka. Elected in 2024 on an Indian National Congress ticket, she is one of the youngest MPs in the 18th Lok Sabha.',
        'biography_kn': 'ಪ್ರಿಯಾಂಕಾ ಜಾರಕಿಹೊಳಿ ಅವರು ಕರ್ನಾಟಕದ ಚಿಕ್ಕೋಡಿ ಲೋಕಸಭಾ ಕ್ಷೇತ್ರವನ್ನು ಪ್ರತಿನಿಧಿಸುವ ಸಂಸದರು.',
        'total_assets': 903000000,
        'total_liabilities': 12000000,
    },
    {
        'first_name_en': 'Jagadish',
        'last_name_en': 'Shettar',
        'full_name_en': 'Jagadish Shettar',
        'full_name_kn': 'ಜಗದೀಶ್ ಶೆಟ್ಟರ್',
        'slug': 'jagadish-shettar',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Belagavi',
        'parliamentary_constituency_kn': 'ಬೆಳಗಾವಿ',
        'party_short_name': 'BJP',
        'age': 68,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/jagadish_shettar.jpg',
        'terms_as_mp': 1,
        'terms_as_mla': 6,
        'biography_en': 'Jagadish Shettar is an MP from Belagavi Lok Sabha constituency. He served as the 15th Chief Minister of Karnataka (2012–2013) and Speaker of the Legislative Assembly.',
        'biography_kn': 'ಜಗದೀಶ್ ಶೆಟ್ಟರ್ ಅವರು ಬೆಳಗಾವಿ ಕ್ಷೇತ್ರದ ಸಂಸದರು ಮತ್ತು ಕರ್ನಾಟಕದ ಮಾಜಿ ಮುಖ್ಯಮಂತ್ರಿಗಳು.',
        'total_assets': 145000000,
        'total_liabilities': 5000000,
    },
    {
        'first_name_en': 'Gaddigoudar',
        'last_name_en': 'Parvthagouda',
        'full_name_en': 'P. C. Gaddigoudar',
        'full_name_kn': 'ಪಿ. ಸಿ. ಗದ್ದಿಗೌಡರ',
        'slug': 'p-c-gaddigoudar',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Bagalkot',
        'parliamentary_constituency_kn': 'ಬಾಗಲಕೋಟೆ',
        'party_short_name': 'BJP',
        'age': 72,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/pc_gaddigoudar.jpg',
        'terms_as_mp': 5,
        'biography_en': 'P. C. Gaddigoudar is a senior politician serving his fifth term as Member of Parliament for the Bagalkot Lok Sabha constituency.',
        'biography_kn': 'ಪಿ. ಸಿ. ಗದ್ದಿಗೌಡರ ಅವರು ಬಾಗಲಕೋಟೆ ಲೋಕಸಭಾ ಕ್ಷೇತ್ರದ ಸಂಸದರಾಗಿದ್ದಾರೆ.',
        'total_assets': 221000000,
        'total_liabilities': 18000000,
    },
    {
        'first_name_en': 'Ramesh',
        'last_name_en': 'Jigajinagi',
        'full_name_en': 'Ramesh Jigajinagi',
        'full_name_kn': 'ರಮೇಶ್ ಜಿಗಜಿಣಗಿ',
        'slug': 'ramesh-jigajinagi',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Bijapur',
        'parliamentary_constituency_kn': 'ವಿಜಯಪುರ',
        'party_short_name': 'BJP',
        'age': 71,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/ramesh_jigajinagi.jpg',
        'terms_as_mp': 6,
        'biography_en': 'Ramesh Jigajinagi is a veteran politician representing the Bijapur constituency. He previously served as Union Minister of State for Drinking Water and Sanitation.',
        'biography_kn': 'ರಮೇಶ್ ಜಿಗಜಿಣಗಿ ಅವರು ವಿಜಯಪುರ ಲೋಕಸಭಾ ಕ್ಷೇತ್ರದ ಹಿರಿಯ ಸಂಸದರು.',
        'total_assets': 502000000,
        'total_liabilities': 32000000,
    },
    {
        'first_name_en': 'Radhakrishna',
        'last_name_en': 'Doddamani',
        'full_name_en': 'Radhakrishna Doddamani',
        'full_name_kn': 'ರಾಧಾಕೃಷ್ಣ ದೊಡ್ಡಮನಿ',
        'slug': 'radhakrishna-doddamani',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Kalaburagi',
        'parliamentary_constituency_kn': 'ಕಲಬುರಗಿ',
        'party_short_name': 'INC',
        'age': 55,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/radhakrishna_doddamani.jpg',
        'terms_as_mp': 1,
        'biography_en': 'Radhakrishna Doddamani is a Member of Parliament for Kalaburagi Lok Sabha constituency, elected in the 2024 general elections.',
        'biography_kn': 'ರಾಧಾಕೃಷ್ಣ ದೊಡ್ಡಮನಿ ಅವರು ಕಲಬುರಗಿ ಲೋಕಸಭಾ ಕ್ಷೇತ್ರದ ಸಂಸದರಾಗಿದ್ದಾರೆ.',
        'total_assets': 284000000,
        'total_liabilities': 15000000,
    },
    {
        'first_name_en': 'G.',
        'last_name_en': 'Kumar Naik',
        'full_name_en': 'G. Kumar Naik',
        'full_name_kn': 'ಜಿ. ಕುಮಾರ್ ನಾಯಕ್',
        'slug': 'g-kumar-naik',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Raichur',
        'parliamentary_constituency_kn': 'ರಾಯಚೂರು',
        'party_short_name': 'INC',
        'age': 61,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/kumar_naik.jpg',
        'terms_as_mp': 1,
        'biography_en': 'G. Kumar Naik is a former senior IAS officer and current Member of Parliament representing Raichur Lok Sabha constituency.',
        'biography_kn': 'ಜಿ. ಕುಮಾರ್ ನಾಯಕ್ ಅವರು ರಾಯಚೂರು ಲೋಕಸಭಾ ಕ್ಷೇತ್ರದ ಸಂಸದರು ಹಾಗೂ ನಿವೃತ್ತ ಐಎಎಸ್ ಅಧಿಕಾರಿ.',
        'total_assets': 128000000,
        'total_liabilities': 4000000,
    },
    {
        'first_name_en': 'Sagar',
        'last_name_en': 'Khandre',
        'full_name_en': 'Sagar Khandre',
        'full_name_kn': 'ಸಾಗರ್ ಖಂಡ್ರೆ',
        'slug': 'sagar-khandre',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Bidar',
        'parliamentary_constituency_kn': 'ಬೀದರ್',
        'party_short_name': 'INC',
        'age': 26,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/sagar_khandre.jpg',
        'terms_as_mp': 1,
        'biography_en': 'Sagar Khandre is an MP from Bidar constituency. At 26 years old, he is one of the youngest representatives elected to the 18th Lok Sabha.',
        'biography_kn': 'ಸಾಗರ್ ಖಂಡ್ರೆ ಅವರು ಬೀದರ್ ಕ್ಷೇತ್ರದ ಸಂಸದರಾಗಿದ್ದಾರೆ.',
        'total_assets': 185000000,
        'total_liabilities': 9000000,
    },
    {
        'first_name_en': 'K.',
        'last_name_en': 'Rajashekar Hitnal',
        'full_name_en': 'K. Rajashekar Basavaraj Hitnal',
        'full_name_kn': 'ಕೆ. ರಾಜಶೇಖರ್ ಬಸವರಾಜ್ ಹಿಟ್ನಾಳ್',
        'slug': 'rajashekar-hitnal',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Koppal',
        'parliamentary_constituency_kn': 'ಕೊಪ್ಪಳ',
        'party_short_name': 'INC',
        'age': 45,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/rajashekar_hitnal.jpg',
        'terms_as_mp': 1,
        'biography_en': 'K. Rajashekar Hitnal represents Koppal constituency in the Lok Sabha.',
        'biography_kn': 'ಕೆ. ರಾಜಶೇಖರ್ ಹಿಟ್ನಾಳ್ ಕೊಪ್ಪಳ ಕ್ಷೇತ್ರದ ಸಂಸದರಾಗಿದ್ದಾರೆ.',
        'total_assets': 156000000,
        'total_liabilities': 7000000,
    },
    {
        'first_name_en': 'E.',
        'last_name_en': 'Tukaram',
        'full_name_en': 'E. Tukaram',
        'full_name_kn': 'ಈ. ತುಕಾರಾಮ್',
        'slug': 'e-tukaram',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Ballari',
        'parliamentary_constituency_kn': 'ಬಳ್ಳಾರಿ',
        'party_short_name': 'INC',
        'age': 56,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/e_tukaram.jpg',
        'terms_as_mp': 1,
        'terms_as_mla': 4,
        'biography_en': 'E. Tukaram is a 4-time MLA and current Member of Parliament representing Ballari Lok Sabha constituency.',
        'biography_kn': 'ಈ. ತುಕಾರಾಮ್ ಅವರು ಬಳ್ಳಾರಿ ಲೋಕಸಭಾ ಕ್ಷೇತ್ರದ ಸಂಸದರಾಗಿದ್ದಾರೆ.',
        'total_assets': 98000000,
        'total_liabilities': 3500000,
    },
    {
        'first_name_en': 'Basavaraj',
        'last_name_en': 'Bommai',
        'full_name_en': 'Basavaraj Bommai',
        'full_name_kn': 'ಬಸವರಾಜ ಬೊಮ್ಮಾಯಿ',
        'slug': 'basavaraj-bommai',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Haveri',
        'parliamentary_constituency_kn': 'ಹಾವೇರಿ',
        'party_short_name': 'BJP',
        'age': 64,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/basavaraj_bommai.jpg',
        'terms_as_mp': 1,
        'terms_as_mla': 4,
        'biography_en': 'Basavaraj Bommai served as the 23rd Chief Minister of Karnataka (2021–2023) and is currently the Member of Parliament for Haveri Lok Sabha constituency.',
        'biography_kn': 'ಬಸವರಾಜ ಬೊಮ್ಮಾಯಿ ಅವರು ಕರ್ನಾಟಕದ 23ನೇ ಮುಖ್ಯಮಂತ್ರಿಗಳಾಗಿದ್ದರು ಮತ್ತು ಪ್ರಸ್ತುತ ಹಾವೇರಿ ಕ್ಷೇತ್ರದ ಸಂಸದರು.',
        'total_assets': 524000000,
        'total_liabilities': 42000000,
    },
    {
        'first_name_en': 'Pralhad',
        'last_name_en': 'Joshi',
        'full_name_en': 'Pralhad Joshi',
        'full_name_kn': 'ಪ್ರಲ್ಹಾದ್ ಜೋಶಿ',
        'slug': 'pralhad-joshi',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Dharwad',
        'parliamentary_constituency_kn': 'ಧಾರವಾಡ',
        'party_short_name': 'BJP',
        'age': 61,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/pralhad_joshi.jpg',
        'terms_as_mp': 5,
        'is_union_minister': True,
        'union_title_en': 'Union Cabinet Minister',
        'union_title_kn': 'ಕೇಂದ್ರ ಸಂಪುಟ ಸಚಿವರು',
        'union_portfolio_en': 'Minister of Consumer Affairs, Food and Public Distribution, and Minister of New and Renewable Energy',
        'union_portfolio_kn': 'ಗ್ರಾಹಕ ವ್ಯವಹಾರಗಳು, ಆಹಾರ ಮತ್ತು ಸಾರ್ವಜನಿಕ ವಿತರಣೆ ಹಾಗೂ ಹೊಸ ಮತ್ತು ನವೀಕರಿಸಬಹುದಾದ ಇಂಧನ ಇಲಾಖೆ',
        'biography_en': 'Pralhad Joshi is a 5-term MP from Dharwad and currently serves as Union Cabinet Minister in Prime Minister Narendra Modi’s government.',
        'biography_kn': 'ಪ್ರಲ್ಹಾದ್ ಜೋಶಿ ಅವರು ಧಾರವಾಡ ಕ್ಷೇತ್ರದ 5 ಬಾರಿಯ ಸಂಸದರು ಮತ್ತು ಕೇಂದ್ರ ಸಂಪುಟ ಸಚಿವರು.',
        'total_assets': 213000000,
        'total_liabilities': 11000000,
    },
    {
        'first_name_en': 'Vishveshwar',
        'last_name_en': 'Kageri',
        'full_name_en': 'Vishveshwar Hegde Kageri',
        'full_name_kn': 'ವಿಶ್ವೇಶ್ವರ ಹೆಗಡೆ ಕಾಗೇರಿ',
        'slug': 'vishveshwar-hegde-kageri',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Uttara Kannada',
        'parliamentary_constituency_kn': 'ಉತ್ತರ ಕನ್ನಡ',
        'party_short_name': 'BJP',
        'age': 63,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/vishveshwar_kageri.jpg',
        'terms_as_mp': 1,
        'terms_as_mla': 6,
        'biography_en': 'Vishveshwar Hegde Kageri is a 6-time former MLA, former Speaker of Karnataka Assembly, and current MP for Uttara Kannada.',
        'biography_kn': 'ವಿಶ್ವೇಶ್ವರ ಹೆಗಡೆ ಕಾಗೇರಿ ಅವರು ಉತ್ತರ ಕನ್ನಡ ಕ್ಷೇತ್ರದ ಸಂಸದರು ಮತ್ತು ವಿಧಾನಸಭೆಯ ಮಾಜಿ ಸ್ಪೀಕರ್.',
        'total_assets': 89000000,
        'total_liabilities': 3000000,
    },
    {
        'first_name_en': 'Prabha',
        'last_name_en': 'Mallikarjun',
        'full_name_en': 'Prabha Mallikarjun',
        'full_name_kn': 'ಪ್ರಭಾ ಮಲ್ಲಿಕಾರ್ಜುನ್',
        'slug': 'prabha-mallikarjun',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Davanagere',
        'parliamentary_constituency_kn': 'ದಾವಣಗೆರೆ',
        'party_short_name': 'INC',
        'age': 48,
        'gender': 'female',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/prabha_mallikarjun.jpg',
        'terms_as_mp': 1,
        'biography_en': 'Prabha Mallikarjun is a healthcare philanthropist, educational administrator, and MP for Davanagere Lok Sabha constituency.',
        'biography_kn': 'ಪ್ರಭಾ ಮಲ್ಲಿಕಾರ್ಜುನ್ ಅವರು ದಾವಣಗೆರೆ ಲೋಕಸಭಾ ಕ್ಷೇತ್ರದ ಸಂಸದರಾಗಿದ್ದಾರೆ.',
        'total_assets': 2415000000,
        'total_liabilities': 180000000,
    },
    {
        'first_name_en': 'B. Y.',
        'last_name_en': 'Raghavendra',
        'full_name_en': 'B. Y. Raghavendra',
        'full_name_kn': 'ಬಿ. ವೈ. ರಾಘವೇಂದ್ರ',
        'slug': 'b-y-raghavendra',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Shimoga',
        'parliamentary_constituency_kn': 'ಶಿವಮೊಗ್ಗ',
        'party_short_name': 'BJP',
        'age': 50,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/by_raghavendra.jpg',
        'terms_as_mp': 4,
        'biography_en': 'B. Y. Raghavendra is a 4-term MP representing the Shimoga constituency in Karnataka.',
        'biography_kn': 'ಬಿ. ವೈ. ರಾಘವೇಂದ್ರ ಅವರು ಶಿವಮೊಗ್ಗ ಲೋಕಸಭಾ ಕ್ಷೇತ್ರದ ಸಂಸದರಾಗಿದ್ದಾರೆ.',
        'total_assets': 732000000,
        'total_liabilities': 65000000,
    },
    {
        'first_name_en': 'Kota',
        'last_name_en': 'Poojary',
        'full_name_en': 'Kota Srinivas Poojary',
        'full_name_kn': 'ಕೋಟ ಶ್ರೀನಿವಾಸ ಪೂಜಾರಿ',
        'slug': 'kota-srinivas-poojary',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Udupi Chikmagalur',
        'parliamentary_constituency_kn': 'ಉಡುಪಿ ಚಿಕ್ಕಮಗಳೂರು',
        'party_short_name': 'BJP',
        'age': 64,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/kota_poojary.jpg',
        'terms_as_mp': 1,
        'biography_en': 'Kota Srinivas Poojary served as Leader of Opposition in Karnataka Legislative Council and is currently MP for Udupi Chikmagalur.',
        'biography_kn': 'ಕೋಟ ಶ್ರೀನಿವಾಸ ಪೂಜಾರಿ ಅವರು ಉಡುಪಿ ಚಿಕ್ಕಮಗಳೂರು ಕ್ಷೇತ್ರದ ಸಂಸದರಾಗಿದ್ದಾರೆ.',
        'total_assets': 45000000,
        'total_liabilities': 1500000,
    },
    {
        'first_name_en': 'Shreyas',
        'last_name_en': 'Patel',
        'full_name_en': 'Shreyas M. Patel',
        'full_name_kn': 'ಶ್ರೇಯಸ್ ಎಂ. ಪಟೇಲ್',
        'slug': 'shreyas-m-patel',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Hassan',
        'parliamentary_constituency_kn': 'ಹಾಸನ',
        'party_short_name': 'INC',
        'age': 32,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/shreyas_patel.jpg',
        'terms_as_mp': 1,
        'biography_en': 'Shreyas M. Patel is an INC politician and MP for Hassan Lok Sabha constituency.',
        'biography_kn': 'ಶ್ರೇಯಸ್ ಎಂ. ಪಟೇಲ್ ಅವರು ಹಾಸನ ಲೋಕಸಭಾ ಕ್ಷೇತ್ರದ ಸಂಸದರಾಗಿದ್ದಾರೆ.',
        'total_assets': 386000000,
        'total_liabilities': 22000000,
    },
    {
        'first_name_en': 'Bricesh',
        'last_name_en': 'Chowta',
        'full_name_en': 'Captain Bricesh Chowta',
        'full_name_kn': 'ಕ್ಯಾಪ್ಟನ್ ಬ್ರಿಜೇಶ್ ಚೌಟ',
        'slug': 'bricesh-chowta',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Dakshina Kannada',
        'parliamentary_constituency_kn': 'ದಕ್ಷಿಣ ಕನ್ನಡ',
        'party_short_name': 'BJP',
        'age': 42,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/bricesh_chowta.jpg',
        'terms_as_mp': 1,
        'biography_en': 'Captain Bricesh Chowta is a former Indian Army officer and current Member of Parliament for Dakshina Kannada.',
        'biography_kn': 'ಕ್ಯಾಪ್ಟನ್ ಬ್ರಿಜೇಶ್ ಚೌಟ ಅವರು ದಕ್ಷಿಣ ಕನ್ನಡ ಲೋಕಸಭಾ ಕ್ಷೇತ್ರದ ಸಂಸದರು.',
        'total_assets': 32000000,
        'total_liabilities': 2000000,
    },
    {
        'first_name_en': 'Govind',
        'last_name_en': 'Karjol',
        'full_name_en': 'Govind Karjol',
        'full_name_kn': 'ಗೋವಿಂದ ಕಾರಜೋಳ',
        'slug': 'govind-karjol',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Chitradurga',
        'parliamentary_constituency_kn': 'ಚಿತ್ರದುರ್ಗ',
        'party_short_name': 'BJP',
        'age': 73,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/govind_karjol.jpg',
        'terms_as_mp': 1,
        'terms_as_mla': 5,
        'biography_en': 'Govind Karjol is a former Deputy Chief Minister of Karnataka and current Member of Parliament for Chitradurga constituency.',
        'biography_kn': 'ಗೋವಿಂದ ಕಾರಜೋಳ ಅವರು ಚಿತ್ರದುರ್ಗ ಕ್ಷೇತ್ರದ ಸಂಸದರು ಮತ್ತು ಮಾಜಿ ಉಪ ಮುಖ್ಯಮಂತ್ರಿಗಳು.',
        'total_assets': 114000000,
        'total_liabilities': 6000000,
    },
    {
        'first_name_en': 'V.',
        'last_name_en': 'Somanna',
        'full_name_en': 'V. Somanna',
        'full_name_kn': 'ವಿ. ಸೋಮಣ್ಣ',
        'slug': 'v-somanna',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Tumkur',
        'parliamentary_constituency_kn': 'ತುಮಕೂರು',
        'party_short_name': 'BJP',
        'age': 73,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/v_somanna.jpg',
        'terms_as_mp': 1,
        'is_union_minister': True,
        'union_title_en': 'Union Minister of State',
        'union_title_kn': 'ಕೇಂದ್ರ ರಾಜ್ಯ ಸಚಿವರು',
        'union_portfolio_en': 'Minister of State for Jal Shakti and Railways',
        'union_portfolio_kn': 'ಜಲಶಕ್ತಿ ಮತ್ತು ರೈಲ್ವೆ ಇಲಾಖೆಯ ರಾಜ್ಯ ಸಚಿವರು',
        'biography_en': 'V. Somanna is MP for Tumkur and currently serves as Union Minister of State in the Government of India.',
        'biography_kn': 'ವಿ. ಸೋಮಣ್ಣ ಅವರು ತುಮಕೂರು ಕ್ಷೇತ್ರದ ಸಂಸದರು ಹಾಗೂ ಕೇಂದ್ರ ಸಚಿವರು.',
        'total_assets': 458000000,
        'total_liabilities': 28000000,
    },
    {
        'first_name_en': 'H. D.',
        'last_name_en': 'Kumaraswamy',
        'full_name_en': 'H. D. Kumaraswamy',
        'full_name_kn': 'ಹೆಚ್. ಡಿ. ಕುಮಾರಸ್ವಾಮಿ',
        'slug': 'h-d-kumaraswamy',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Mandya',
        'parliamentary_constituency_kn': 'ಮಂಡ್ಯ',
        'party_short_name': 'JD(S)',
        'age': 64,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/hd_kumaraswamy.jpg',
        'terms_as_mp': 3,
        'terms_as_mla': 4,
        'is_union_minister': True,
        'union_title_en': 'Union Cabinet Minister',
        'union_title_kn': 'ಕೇಂದ್ರ ಸಂಪುಟ ಸಚಿವರು',
        'union_portfolio_en': 'Minister of Heavy Industries and Minister of Steel',
        'union_portfolio_kn': 'ಬೃಹತ್ ಕೈಗಾರಿಕೆಗಳು ಮತ್ತು ಉಕ್ಕು ಇಲಾಖೆ ಕೇಂದ್ರ ಸಚಿವರು',
        'biography_en': 'H. D. Kumaraswamy served twice as Chief Minister of Karnataka and currently serves as Union Cabinet Minister for Heavy Industries and Steel.',
        'biography_kn': 'ಹೆಚ್. ಡಿ. ಕುಮಾರಸ್ವಾಮಿ ಅವರು ಕರ್ನಾಟಕದ ಮಾಜಿ ಮುಖ್ಯಮಂತ್ರಿಗಳು ಮತ್ತು ಕೇಂದ್ರ ಸಂಪುಟ ಸಚಿವರು.',
        'total_assets': 2172000000,
        'total_liabilities': 190000000,
    },
    {
        'first_name_en': 'Yaduveer',
        'last_name_en': 'Wadiyar',
        'full_name_en': 'Yaduveer Krishnadatta Chamaraja Wadiyar',
        'full_name_kn': 'ಯದುವೀರ ಕೃಷ್ಣದತ್ತ ಚಾಮರಾಜ ಒಡೆಯರ್',
        'slug': 'yaduveer-wadiyar',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Mysore',
        'parliamentary_constituency_kn': 'ಮೈಸೂರು',
        'party_short_name': 'BJP',
        'age': 32,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/yaduveer_wadiyar.jpg',
        'terms_as_mp': 1,
        'biography_en': 'Yaduveer Wadiyar is the head of the former royal family of Mysore and current Member of Parliament for the Mysore Lok Sabha constituency.',
        'biography_kn': 'ಯದುವೀರ ಒಡೆಯರ್ ಅವರು ಮೈಸೂರು ರಾಜಮನೆತನದ ಮುಖ್ಯಸ್ಥರು ಮತ್ತು ಮೈಸೂರು ಕ್ಷೇತ್ರದ ಸಂಸದರು.',
        'total_assets': 50000000,
        'total_liabilities': 0,
    },
    {
        'first_name_en': 'Sunil',
        'last_name_en': 'Bose',
        'full_name_en': 'Sunil Bose',
        'full_name_kn': 'ಸುನಿಲ್ ಬೋಸ್',
        'slug': 'sunil-bose',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Chamarajanagar',
        'parliamentary_constituency_kn': 'ಚಾಮರಾಜನಗರ',
        'party_short_name': 'INC',
        'age': 41,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/sunil_bose.jpg',
        'terms_as_mp': 1,
        'biography_en': 'Sunil Bose is an INC politician representing the Chamarajanagar constituency in Lok Sabha.',
        'biography_kn': 'ಸುನಿಲ್ ಬೋಸ್ ಚಾಮರಾಜನಗರ ಲೋಕಸಭಾ ಕ್ಷೇತ್ರದ ಸಂಸದರಾಗಿದ್ದಾರೆ.',
        'total_assets': 142000000,
        'total_liabilities': 8000000,
    },
    {
        'first_name_en': 'Dr. C. N.',
        'last_name_en': 'Manjunath',
        'full_name_en': 'Dr. C. N. Manjunath',
        'full_name_kn': 'ಡಾ. ಸಿ. ಎನ್. ಮಂಜುನಾಥ್',
        'slug': 'dr-c-n-manjunath',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Bangalore Rural',
        'parliamentary_constituency_kn': 'ಬೆಂಗಳೂರು ಗ್ರಾಮಾಂತರ',
        'party_short_name': 'BJP',
        'age': 66,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/dr_cn_manjunath.jpg',
        'terms_as_mp': 1,
        'biography_en': 'Dr. C. N. Manjunath is a Padma Shri recipient, eminent cardiologist, former Director of Jayadeva Institute of Cardiovascular Sciences, and MP for Bangalore Rural.',
        'biography_kn': 'ಡಾ. ಸಿ. ಎನ್. ಮಂಜುನಾಥ್ ಅವರು ಪದ್ಮಶ್ರೀ ಪುರಸ್ಕೃತ ಹೃದ್ರೋಗ ತಜ್ಞರು ಮತ್ತು ಬೆಂಗಳೂರು ಗ್ರಾಮಾಂತರ ಕ್ಷೇತ್ರದ ಸಂಸದರು.',
        'total_assets': 984000000,
        'total_liabilities': 45000000,
    },
    {
        'first_name_en': 'Shobha',
        'last_name_en': 'Karandlaje',
        'full_name_en': 'Shobha Karandlaje',
        'full_name_kn': 'ಶೋಭಾ ಕರಂದ್ಲಾಜೆ',
        'slug': 'shobha-karandlaje',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Bangalore North',
        'parliamentary_constituency_kn': 'ಬೆಂಗಳೂರು ಉತ್ತರ',
        'party_short_name': 'BJP',
        'age': 57,
        'gender': 'female',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/shobha_karandlaje.jpg',
        'terms_as_mp': 3,
        'is_union_minister': True,
        'union_title_en': 'Union Minister of State',
        'union_title_kn': 'ಕೇಂದ್ರ ರಾಜ್ಯ ಸಚಿವರು',
        'union_portfolio_en': 'Minister of State for Micro, Small and Medium Enterprises, and Labour & Employment',
        'union_portfolio_kn': 'ಸೂಕ್ಷ್ಮ, ಸಣ್ಣ ಮತ್ತು ಮಧ್ಯಮ ಉದ್ಯಮಗಳು ಹಾಗೂ ಕಾರ್ಮಿಕ ಮತ್ತು ಉದ್ಯೋಗ ಇಲಾಖೆ ಕೇಂದ್ರ ಸಚಿವರು',
        'biography_en': 'Shobha Karandlaje is a 3-term MP representing Bangalore North and serves as Union Minister of State in the Government of India.',
        'biography_kn': 'ಶೋಭಾ ಕರಂದ್ಲಾಜೆ ಅವರು ಬೆಂಗಳೂರು ಉತ್ತರ ಕ್ಷೇತ್ರದ ಸಂಸದರು ಹಾಗೂ ಕೇಂದ್ರ ರಾಜ್ಯ ಸಚಿವರು.',
        'total_assets': 138000000,
        'total_liabilities': 6000000,
    },
    {
        'first_name_en': 'P. C.',
        'last_name_en': 'Mohan',
        'full_name_en': 'P. C. Mohan',
        'full_name_kn': 'ಪಿ. ಸಿ. ಮೋಹನ್',
        'slug': 'p-c-mohan',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Bangalore Central',
        'parliamentary_constituency_kn': 'ಬೆಂಗಳೂರು ಸೆಂಟ್ರಲ್',
        'party_short_name': 'BJP',
        'age': 60,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/pc_mohan.jpg',
        'terms_as_mp': 4,
        'biography_en': 'P. C. Mohan is a 4-term Member of Parliament representing the Bangalore Central constituency.',
        'biography_kn': 'ಪಿ. ಸಿ. ಮೋಹನ್ ಅವರು ಬೆಂಗಳೂರು ಸೆಂಟ್ರಲ್ ಕ್ಷೇತ್ರದ 4 ಬಾರಿಯ ಸಂಸದರು.',
        'total_assets': 756000000,
        'total_liabilities': 50000000,
    },
    {
        'first_name_en': 'Tejasvi',
        'last_name_en': 'Surya',
        'full_name_en': 'Tejasvi Surya',
        'full_name_kn': 'ತೇಜಸ್ವಿ ಸೂರ್ಯ',
        'slug': 'tejasvi-surya',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Bangalore South',
        'parliamentary_constituency_kn': 'ಬೆಂಗಳೂರು ದಕ್ಷಿಣ',
        'party_short_name': 'BJP',
        'age': 33,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/tejasvi_surya.jpg',
        'terms_as_mp': 2,
        'biography_en': 'Tejasvi Surya is a 2-term Member of Parliament representing Bangalore South and serves as National President of Bharatiya Janata Yuva Morcha.',
        'biography_kn': 'ತೇಜಸ್ವಿ ಸೂರ್ಯ ಅವರು ಬೆಂಗಳೂರು ದಕ್ಷಿಣ ಕ್ಷೇತ್ರದ ಸಂಸದರು ಮತ್ತು ಯುವ ಮೋರ್ಚಾ ರಾಷ್ಟ್ರೀಯ ಅಧ್ಯಕ್ಷರು.',
        'total_assets': 41000000,
        'total_liabilities': 1000000,
    },
    {
        'first_name_en': 'Dr. K.',
        'last_name_en': 'Sudhakar',
        'full_name_en': 'Dr. K. Sudhakar',
        'full_name_kn': 'ಡಾ. ಕೆ. ಸುಧಾಕರ್',
        'slug': 'dr-k-sudhakar',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Chikkballapur',
        'parliamentary_constituency_kn': 'ಚಿಕ್ಕಬಳ್ಳಾಪುರ',
        'party_short_name': 'BJP',
        'age': 50,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/dr_k_sudhakar.jpg',
        'terms_as_mp': 1,
        'terms_as_mla': 2,
        'biography_en': 'Dr. K. Sudhakar is a former Health Minister of Karnataka and current Member of Parliament for Chikkballapur constituency.',
        'biography_kn': 'ಡಾ. ಕೆ. ಸುಧಾಕರ್ ಅವರು ಚಿಕ್ಕಬಳ್ಳಾಪುರ ಕ್ಷೇತ್ರದ ಸಂಸದರು ಮತ್ತು ಮಾಜಿ ಆರೋಗ್ಯ ಸಚಿವರು.',
        'total_assets': 327000000,
        'total_liabilities': 18000000,
    },
    {
        'first_name_en': 'M.',
        'last_name_en': 'Mallesh Babu',
        'full_name_en': 'M. Mallesh Babu',
        'full_name_kn': 'ಎಮ್. ಮಲ್ಲೇಶ್ ಬಾಬು',
        'slug': 'm-mallesh-babu',
        'representative_type': 'mp_ls',
        'parliamentary_constituency_en': 'Kolar',
        'parliamentary_constituency_kn': 'ಕೋಲಾರ',
        'party_short_name': 'JD(S)',
        'age': 46,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/mallesh_babu.jpg',
        'terms_as_mp': 1,
        'biography_en': 'M. Mallesh Babu is a JD(S) politician representing the Kolar Lok Sabha constituency.',
        'biography_kn': 'ಎಮ್. ಮಲ್ಲೇಶ್ ಬಾಬು ಅವರು ಕೋಲಾರ ಲೋಕಸಭಾ ಕ್ಷೇತ್ರದ ಸಂಸದರಾಗಿದ್ದಾರೆ.',
        'total_assets': 164000000,
        'total_liabilities': 11000000,
    },
    {
        'first_name_en': 'Nirmala',
        'last_name_en': 'Sitharaman',
        'full_name_en': 'Nirmala Sitharaman',
        'full_name_kn': 'ನಿರ್ಮಲಾ ಸೀತಾರಾಮನ್',
        'slug': 'nirmala-sitharaman',
        'representative_type': 'mp_rs',
        'parliamentary_constituency_en': 'Karnataka (Rajya Sabha)',
        'parliamentary_constituency_kn': 'ಕರ್ನಾಟಕ (ರಾಜ್ಯಸಭೆ)',
        'party_short_name': 'BJP',
        'age': 64,
        'gender': 'female',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/nirmala_sitharaman.jpg',
        'terms_as_mp': 3,
        'is_union_minister': True,
        'union_title_en': 'Union Cabinet Minister',
        'union_title_kn': 'ಕೇಂದ್ರ ಸಂಪುಟ ಸಚಿವರು',
        'union_portfolio_en': 'Minister of Finance and Minister of Corporate Affairs',
        'union_portfolio_kn': 'ಹಣಕಾಸು ಮತ್ತು ಕಾರ್ಪೊರೇಟ್ ವ್ಯವಹಾರಗಳ ಕೇಂದ್ರ ಸಚಿವರು',
        'biography_en': 'Nirmala Sitharaman represents Karnataka in the Rajya Sabha and serves as Union Minister of Finance and Corporate Affairs of India. She previously served as Defence Minister of India and Commerce Minister.',
        'biography_kn': 'ನಿರ್ಮಲಾ ಸೀತಾರಾಮನ್ ಅವರು ಕರ್ನಾಟಕದಿಂದ ರಾಜ್ಯಸಭಾ ಸಂಸದರು ಮತ್ತು ಭಾರತದ ಕೇಂದ್ರ ಹಣಕಾಸು ಸಚಿವರು.',
        'total_assets': 25000000,
        'total_liabilities': 3000000,
    },
    {
        'first_name_en': 'Mallikarjun',
        'last_name_en': 'Kharge',
        'full_name_en': 'Mallikarjun Kharge',
        'full_name_kn': 'ಮಲ್ಲಿಕಾರ್ಜುನ ಖರ್ಗೆ',
        'slug': 'mallikarjun-kharge',
        'representative_type': 'mp_rs',
        'parliamentary_constituency_en': 'Karnataka (Rajya Sabha)',
        'parliamentary_constituency_kn': 'ಕರ್ನಾಟಕ (ರಾಜ್ಯಸಭೆ)',
        'party_short_name': 'INC',
        'age': 81,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/mallikarjun_kharge.jpg',
        'terms_as_mp': 4,
        'terms_as_mla': 9,
        'biography_en': 'Mallikarjun Kharge is the President of the Indian National Congress and Leader of the Opposition in the Rajya Sabha representing Karnataka. A veteran parliamentarian, he won 9 consecutive Assembly elections and served as Union Minister for Railways and Labour.',
        'biography_kn': 'ಮಲ್ಲಿಕಾರ್ಜುನ ಖರ್ಗೆ ಅವರು ಎಐಸಿಸಿ ಅಧ್ಯಕ್ಷರು, ರಾಜ್ಯಸಭೆಯ ವಿರೋಧ ಪಕ್ಷದ ನಾಯಕರು ಮತ್ತು ಕರ್ನಾಟಕದ ಹಿರಿಯ ನಾಯಕರು.',
        'total_assets': 218000000,
        'total_liabilities': 12000000,
    },
    {
        'first_name_en': 'H. D.',
        'last_name_en': 'Deve Gowda',
        'full_name_en': 'H. D. Deve Gowda',
        'full_name_kn': 'ಹೆಚ್. ಡಿ. ದೇವೇಗೌಡ',
        'slug': 'h-d-deve-gowda',
        'representative_type': 'mp_rs',
        'parliamentary_constituency_en': 'Karnataka (Rajya Sabha)',
        'parliamentary_constituency_kn': 'ಕರ್ನಾಟಕ (ರಾಜ್ಯಸಭೆ)',
        'party_short_name': 'JD(S)',
        'age': 91,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/hd_devegowda.jpg',
        'terms_as_mp': 7,
        'terms_as_mla': 6,
        'biography_en': 'H. D. Deve Gowda served as the 11th Prime Minister of India (1996–1997) and 14th Chief Minister of Karnataka. He is the National President of Janata Dal (Secular) and currently represents Karnataka in the Rajya Sabha.',
        'biography_kn': 'ಹೆಚ್. ಡಿ. ದೇವೇಗೌಡ ಅವರು ಭಾರತದ 11ನೇ ಪ್ರಧಾನ ಮಂತ್ರಿಗಳು ಮತ್ತು ಪ್ರಸ್ತುತ ರಾಜ್ಯಸಭಾ ಸಂಸದರು.',
        'total_assets': 154000000,
        'total_liabilities': 8000000,
    },
    {
        'first_name_en': 'Syed',
        'last_name_en': 'Naseer Hussain',
        'full_name_en': 'Dr. Syed Naseer Hussain',
        'full_name_kn': 'ಡಾ. ಸೈಯದ್ ನಸೀರ್ ಹುಸೇನ್',
        'slug': 'syed-naseer-hussain',
        'representative_type': 'mp_rs',
        'parliamentary_constituency_en': 'Karnataka (Rajya Sabha)',
        'parliamentary_constituency_kn': 'ಕರ್ನಾಟಕ (ರಾಜ್ಯಸಭೆ)',
        'party_short_name': 'INC',
        'age': 53,
        'gender': 'male',
        'photo_url': 'https://myneta.info/images_candidate/Karnataka2024/syed_naseer_hussain.jpg',
        'terms_as_mp': 2,
        'biography_en': 'Dr. Syed Naseer Hussain is a 2-term Member of Parliament in the Rajya Sabha representing Karnataka and serves as Senior Spokesperson for the Indian National Congress.',
        'biography_kn': 'ಡಾ. ಸೈಯದ್ ನಸೀರ್ ಹುಸೇನ್ ಅವರು ಕರ್ನಾಟಕದಿಂದ ರಾಜ್ಯಸಭಾ ಸಂಸದರು.',
        'total_assets': 85000000,
        'total_liabilities': 4000000,
    }
]

class Command(BaseCommand):
    help = 'Seeds all 28 Karnataka Lok Sabha Members of Parliament (2024) and Union Ministers'

    def handle(self, *args, **kwargs):
        bjp_party = Party.objects.filter(party_short_name_en__icontains='BJP').first()
        inc_party = Party.objects.filter(party_short_name_en__icontains='INC').first()
        jds_party = Party.objects.filter(party_short_name_en__icontains='JD').first()

        created_count = 0
        updated_count = 0

        for item in KARNATAKA_MPS:
            party_code = item.pop('party_short_name')
            total_assets = item.pop('total_assets', 0)
            total_liabilities = item.pop('total_liabilities', 0)

            party = bjp_party if party_code == 'BJP' else (inc_party if party_code == 'INC' else jds_party)

            pol, created = Politician.objects.update_or_create(
                slug=item['slug'],
                defaults={
                    **item,
                    'current_party': party,
                    'is_active': True,
                    'is_verified': True,
                }
            )

            if total_assets > 0:
                FinancialDeclaration.objects.update_or_create(
                    politician=pol,
                    declaration_year=2024,
                    defaults={
                        'declaration_type': 'election',
                        'total_assets': total_assets,
                        'total_liabilities': total_liabilities,
                    }
                )

            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'Created MP: {pol.full_name_en} ({pol.parliamentary_constituency_en})'))
            else:
                updated_count += 1
                self.stdout.write(self.style.SUCCESS(f'Updated MP: {pol.full_name_en} ({pol.parliamentary_constituency_en})'))

        self.stdout.write(self.style.SUCCESS(f'\nFinished Seeding Karnataka MPs! Created: {created_count}, Updated: {updated_count}'))
